name: brain-fuel
recipe: laravel
config:
  via: nginx
  webroot: public
  xdebug: true
  php: 7.3
  database: mysql
tooling:
  node:
    service: node
  npm:
    service: node
  # Server Helpers
  setup:
    description: First-time setup command
    service: appserver
    cmd:
      - composer install
      - cp /app/.env.example /app/.env
      - php artisan key:generate
      - php artisan migrate
